[general]
language = ""
skin = "config/skin/white.qss"

[file]
recent = []
recentcount = 8

[CodeEditor]
fontsize = 11

[advance]
autoexportqss = "1seees"

[update]
autocheck = ""
checkfreq = ""
lastcheckday = 2022-03-29
