# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/main_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(829, 598)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icon/app.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("QWidget#centralwidget{\n"
" border-image: url(:/img/fish.png);\n"
"}\n"
"\n"
"QWidget#widget{\n"
" background-color:rgba(0,0,0,0);\n"
"}\n"
"\n"
"QTextBrowser#textBrowser{\n"
" background-color:rgba(0,0,0,0);\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setAutoFillBackground(False)
        self.widget.setStyleSheet("")
        self.widget.setObjectName("widget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.is_min_status_checkBox = QtWidgets.QCheckBox(self.widget)
        self.is_min_status_checkBox.setObjectName("is_min_status_checkBox")
        self.verticalLayout_2.addWidget(self.is_min_status_checkBox)
        self.textBrowser = QtWidgets.QTextBrowser(self.widget)
        self.textBrowser.setObjectName("textBrowser")
        self.verticalLayout_2.addWidget(self.textBrowser)
        self.verticalLayout.addWidget(self.widget)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.is_min_status_checkBox.setText(_translate("MainWindow", "最小化到任务栏图标"))
        self.textBrowser.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:10px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><a name=\"cb_post_title_url\"></a><a href=\"https://www.cnblogs.com/wowk/p/3162271.html\"><span style=\" font-family:\'PingFang SC\',\'Microsoft YaHei\',\'Helvetica Neue\',\'Helvetica\',\'Arial\',\'sans-serif\'; font-weight:600; text-decoration: underline; color:#4371a6; vertical-align:middle;\">Q</span></a><span style=\" font-family:\'PingFang SC\',\'Microsoft YaHei\',\'Helvetica Neue\',\'Helvetica\',\'Arial\',\'sans-serif\'; font-weight:600; color:#4371a6; vertical-align:middle;\">t5：QSystemTrayIcon类实现程序托盘图标</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:10px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><a name=\"cnblogs_post_body\"></a><span style=\" font-family:\'PingFang SC\',\'Microsoft YaHei\',\'Helvetica Neue\',\'Helvetica\',\'Arial\',\'sans-serif\'; font-size:13px; color:#4b4b4b;\">w</span><span style=\" font-family:\'PingFang SC\',\'Microsoft YaHei\',\'Helvetica Neue\',\'Helvetica\',\'Arial\',\'sans-serif\'; font-size:13px; color:#4b4b4b;\">indows下，在许多应用程序中都会实现一个托盘图标，用于隐藏应用程序窗口时还能对该应用程序进行简单的操作，例如 QQ ，renren等程序</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:10px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'PingFang SC\',\'Microsoft YaHei\',\'Helvetica Neue\',\'Helvetica\',\'Arial\',\'sans-serif\'; font-size:13px; color:#4b4b4b;\">那么，在Qt中，如何实现呢？ 这就要用到Qt提供的 QSystemTrayIcon  这个类了。</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:10px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'PingFang SC\',\'Microsoft YaHei\',\'Helvetica Neue\',\'Helvetica\',\'Arial\',\'sans-serif\'; font-size:13px; color:#4b4b4b;\">来看看这个类中都有哪些常用的成员函数</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:10px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'PingFang SC\',\'Microsoft YaHei\',\'Helvetica Neue\',\'Helvetica\',\'Arial\',\'sans-serif\'; font-size:13px; color:#4b4b4b;\">首先是这个类的构造函数</span></p></body></html>"))
from res import app_rc
