# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/register_form.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Frame(object):
    def setupUi(self, Frame):
        Frame.setObjectName("Frame")
        Frame.resize(621, 602)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icon/icon/首页.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Frame.setWindowIcon(icon)
        self.widget = QtWidgets.QWidget(Frame)
        self.widget.setGeometry(QtCore.QRect(30, 30, 550, 550))
        self.widget.setStyleSheet("QPushButton#register_pushButton{\n"
" background-color:qlineargradient(spread:pad,x1:0,y1:0.505682,x2:1,y2:0.477,stop:0 rgba(11,131,120,219),stop:1 rgba(85,98,112,226));\n"
" color:rgba(255,255,255,210);\n"
" border-radius:5px;\n"
"}\n"
"\n"
"QPushButton#register_pushButton:hover{\n"
" background-color:qlineargradient(spread:pad,x1:0,y1:0.505682,x2:1,y2:0.477,stop:0 rgba(150,123,1111,219),stop:1 rgba(85,81,84,226));\n"
"}\n"
"\n"
"QPushButton#register_pushButton:pressed{\n"
" padding-left:5px;\n"
" padding-top:5px;\n"
" background-color:rgba(150,123,111,255);\n"
"}\n"
"\n"
"QPushButton#forget_password_pushButton,#register_pushButton{\n"
" background-color:rgba(0,0,0,0);\n"
" border:none;\n"
" border-bottom:1px solid rgb(179, 179, 179);\n"
" color:rgba(0,0,0,240);\n"
"}\n"
"\n"
"QPushButton#github_pushButton,#phone_pushButton,#email_pushButton{\n"
" background-color:rgba(0,0,0,0);\n"
" color:rgba(85,98,112,255);\n"
"}\n"
"\n"
"QPushButton#github_pushButton:hover,#phone_pushButton:hover,#email_pushButton:hover{\n"
" color:rgba(131,96,53,255);\n"
"}\n"
"\n"
"QPushButton#github_pushButton:pressed,#phone_pushButton:pressed,#email_pushButton:pressed{\n"
" padding-left:5px;\n"
" padding-top:5px;\n"
" color:rgba(91,88,53,255);\n"
"}\n"
"\n"
"QPushButton#close_pushButton{\n"
" background-color: #ce5137;\n"
" border-radius:10px;\n"
"}\n"
"\n"
"QPushButton#close_pushButton:hover{\n"
" background-size: cover;\n"
" background-image: url(:/icon/icon/close.svg);\n"
"}\n"
"\n"
"QPushButton#min_pushButton{\n"
" background-color: #a1c661;\n"
" border-radius:10px;\n"
"}\n"
"\n"
"QPushButton#min_pushButton:hover{\n"
" background-size: cover;\n"
" background-image: url(:/icon/icon/minimize.svg);\n"
"}\n"
"")
        self.widget.setObjectName("widget")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setGeometry(QtCore.QRect(40, 30, 280, 430))
        self.label.setStyleSheet("border-image: url(:/img/image/register.jpg);\n"
"border-top-left-radius:50px;")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setGeometry(QtCore.QRect(40, 30, 280, 430))
        self.label_2.setStyleSheet("background-color:rgba(0,0,0,80);\n"
"border-top-left-radius:50px;")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.widget)
        self.label_3.setGeometry(QtCore.QRect(270, 30, 240, 430))
        self.label_3.setStyleSheet("background-color:rgba(255,255,255,255);\n"
"border-bottom-right-radius:50px;")
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.widget)
        self.label_4.setGeometry(QtCore.QRect(300, 80, 180, 40))
        self.label_4.setMinimumSize(QtCore.QSize(180, 40))
        self.label_4.setMaximumSize(QtCore.QSize(180, 40))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.label_4.setStyleSheet("color:rgba(0,0,0,200);")
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.user_name_lineEdit = QtWidgets.QLineEdit(self.widget)
        self.user_name_lineEdit.setGeometry(QtCore.QRect(295, 150, 190, 40))
        self.user_name_lineEdit.setMinimumSize(QtCore.QSize(190, 40))
        self.user_name_lineEdit.setMaximumSize(QtCore.QSize(190, 40))
        font = QtGui.QFont()
        font.setFamily("华文楷体")
        font.setPointSize(15)
        self.user_name_lineEdit.setFont(font)
        self.user_name_lineEdit.setStyleSheet("background-color:rgba(0,0,0,0);\n"
"border:none;\n"
"border-bottom:2px solid rgba(46,82,101,200);\n"
"color:rgba(0,0,0,240);\n"
"padding-bottom:7px;")
        self.user_name_lineEdit.setObjectName("user_name_lineEdit")
        self.password_lineEdit = QtWidgets.QLineEdit(self.widget)
        self.password_lineEdit.setGeometry(QtCore.QRect(295, 200, 190, 40))
        self.password_lineEdit.setMinimumSize(QtCore.QSize(190, 40))
        self.password_lineEdit.setMaximumSize(QtCore.QSize(190, 40))
        font = QtGui.QFont()
        font.setFamily("华文楷体")
        font.setPointSize(15)
        self.password_lineEdit.setFont(font)
        self.password_lineEdit.setStyleSheet("background-color:rgba(0,0,0,0);\n"
"border:none;\n"
"border-bottom:2px solid rgba(46,82,101,200);\n"
"color:rgba(0,0,0,240);\n"
"padding-bottom:7px;")
        self.password_lineEdit.setEchoMode(QtWidgets.QLineEdit.Password)
        self.password_lineEdit.setObjectName("password_lineEdit")
        self.register_pushButton = QtWidgets.QPushButton(self.widget)
        self.register_pushButton.setGeometry(QtCore.QRect(295, 330, 190, 40))
        self.register_pushButton.setMinimumSize(QtCore.QSize(190, 40))
        self.register_pushButton.setMaximumSize(QtCore.QSize(190, 40))
        font = QtGui.QFont()
        font.setFamily("华文楷体")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.register_pushButton.setFont(font)
        self.register_pushButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.register_pushButton.setObjectName("register_pushButton")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.widget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(300, 390, 171, 32))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.github_pushButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.github_pushButton.setMinimumSize(QtCore.QSize(30, 30))
        self.github_pushButton.setMaximumSize(QtCore.QSize(30, 30))
        font = QtGui.QFont()
        font.setFamily("Social Media Circled")
        font.setPointSize(15)
        self.github_pushButton.setFont(font)
        self.github_pushButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.github_pushButton.setStyleSheet("")
        self.github_pushButton.setObjectName("github_pushButton")
        self.horizontalLayout.addWidget(self.github_pushButton)
        self.phone_pushButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.phone_pushButton.setMinimumSize(QtCore.QSize(30, 30))
        self.phone_pushButton.setMaximumSize(QtCore.QSize(30, 30))
        font = QtGui.QFont()
        font.setFamily("Social Media Circled")
        font.setPointSize(15)
        self.phone_pushButton.setFont(font)
        self.phone_pushButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.phone_pushButton.setStyleSheet("")
        self.phone_pushButton.setObjectName("phone_pushButton")
        self.horizontalLayout.addWidget(self.phone_pushButton)
        self.email_pushButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.email_pushButton.setMinimumSize(QtCore.QSize(30, 30))
        self.email_pushButton.setMaximumSize(QtCore.QSize(30, 30))
        font = QtGui.QFont()
        font.setFamily("Social Media Circled")
        font.setPointSize(15)
        self.email_pushButton.setFont(font)
        self.email_pushButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.email_pushButton.setStyleSheet("")
        self.email_pushButton.setObjectName("email_pushButton")
        self.horizontalLayout.addWidget(self.email_pushButton)
        self.min_pushButton = QtWidgets.QPushButton(self.widget)
        self.min_pushButton.setGeometry(QtCore.QRect(455, 40, 20, 20))
        self.min_pushButton.setMinimumSize(QtCore.QSize(20, 20))
        self.min_pushButton.setMaximumSize(QtCore.QSize(20, 20))
        self.min_pushButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.min_pushButton.setText("")
        self.min_pushButton.setObjectName("min_pushButton")
        self.close_pushButton = QtWidgets.QPushButton(self.widget)
        self.close_pushButton.setGeometry(QtCore.QRect(480, 40, 20, 20))
        self.close_pushButton.setMinimumSize(QtCore.QSize(20, 20))
        self.close_pushButton.setMaximumSize(QtCore.QSize(20, 20))
        self.close_pushButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.close_pushButton.setText("")
        self.close_pushButton.setObjectName("close_pushButton")
        self.password2_lineEdit = QtWidgets.QLineEdit(self.widget)
        self.password2_lineEdit.setGeometry(QtCore.QRect(295, 250, 190, 40))
        self.password2_lineEdit.setMinimumSize(QtCore.QSize(190, 40))
        self.password2_lineEdit.setMaximumSize(QtCore.QSize(190, 40))
        font = QtGui.QFont()
        font.setFamily("华文楷体")
        font.setPointSize(15)
        self.password2_lineEdit.setFont(font)
        self.password2_lineEdit.setStyleSheet("background-color:rgba(0,0,0,0);\n"
"border:none;\n"
"border-bottom:2px solid rgba(46,82,101,200);\n"
"color:rgba(0,0,0,240);\n"
"padding-bottom:7px;")
        self.password2_lineEdit.setEchoMode(QtWidgets.QLineEdit.Password)
        self.password2_lineEdit.setObjectName("password2_lineEdit")
        self.regsiter_res_label = QtWidgets.QLabel(self.widget)
        self.regsiter_res_label.setGeometry(QtCore.QRect(295, 290, 191, 31))
        font = QtGui.QFont()
        font.setFamily("华文楷体")
        font.setPointSize(10)
        self.regsiter_res_label.setFont(font)
        self.regsiter_res_label.setText("")
        self.regsiter_res_label.setObjectName("regsiter_res_label")

        self.retranslateUi(Frame)
        QtCore.QMetaObject.connectSlotsByName(Frame)

    def retranslateUi(self, Frame):
        _translate = QtCore.QCoreApplication.translate
        Frame.setWindowTitle(_translate("Frame", "Frame"))
        self.label.setText(_translate("Frame", "TextLabel"))
        self.label_4.setText(_translate("Frame", "注册界面"))
        self.user_name_lineEdit.setPlaceholderText(_translate("Frame", "用户名"))
        self.password_lineEdit.setPlaceholderText(_translate("Frame", "密码"))
        self.register_pushButton.setText(_translate("Frame", "注册"))
        self.github_pushButton.setText(_translate("Frame", ")"))
        self.phone_pushButton.setText(_translate("Frame", "#"))
        self.email_pushButton.setText(_translate("Frame", "k"))
        self.password2_lineEdit.setPlaceholderText(_translate("Frame", "再次输入密码"))
from res import app_rc
